[package]
name = "day-5"
version = "0.1.0"
authors = ["François Baldassari <francois@memfault.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
